spring:
  application:
    name: spring-webflux-demo
  webflux:
    base-path: /api
  data:
    mongodb:
      authentication-datebase: admin
      uri: mongodb://localhost:27017/test
      database: test
logging:
  level:
    com:
      kpraveen: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
